apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespaace: default
spec:
  replicas: 3
  selector:
  matchLabels:
    app: web
  template:
    metadata:
      name: web-app-container
      labels:
        app: web
    spec:
      containers:
      - name: web-app-container
        image: nginx
        ports: 
          - containerPort: 80
            protocol: TCP
          - name: http
        volumeMount:
          - name: persistent-volume
            path: /usr/share/nginx/html #where the requested 2gi of data to be mounted, this is the respected path to be mounted.
       volumes:
         - name: persistent-volume
           persistentVolumeClaim:
             claimName: nginx-pvc # awaits to bound from pvc manifest file
             
          
          
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
  type: NodePort #you can access through nodes public ip with nodeport:range  {ex: 172.15.2.63:32654 }
  
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc   #it matches the pvc claim  in pod 
spec:
  accessmodes:
    - ReadWriteOnce  #access type readwriteonce 
  resources:
    requests:
      storage: '2Gi'
      
  
